## Cell 1: Import libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

## Cell 2: Load the dataset

In [2]:
df = pd.read_csv("H:\Amazon Store Sales, Profitability & Returns Analytics\Dataset\Amazon Store Sales Data.xlsx - Sheet1 (1) (1).csv")

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\VIVOBBOK 16\AppData\Local\Temp\ipykernel_32496\4243310338.py:1: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv("H:\Amazon Store Sales, Profitability & Returns Analytics\Dataset\Amazon Store Sales Data.xlsx - Sheet1 (1) (1).csv")

## Cell 3: View the dataset

In [3]:
df.head()

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
0,4918,CA-2019-160304,1/1/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,0,Online
1,4919,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,0,Online
2,4920,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,East,TEC-PH-10000455,Technology,Phones,GE 30522EE2,231.98,2,67.2742,0,Cards
3,3074,CA-2019-125206,1/3/2019,1/5/2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,California,West,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,0,Online
4,8604,US-2019-116365,1/3/2019,1/8/2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,Texas,Central,TEC-AC-10002217,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,0,Online

In [4]:
df.sample(5, random_state=42)

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
3528,9687,CA-2020-116498,5/30/2020,6/3/2020,Standard Class,KA-16525,Kelly Andreada,Consumer,United States,San Diego,California,West,OFF-AR-10003405,Office Supplies,Art,"Dixon My First Ticonderoga Pencil, #2",2049.100,6,10.1790,0,COD
5435,3899,CA-2020-102267,11/30/2020,12/4/2020,Standard Class,SC-20800,Stuart Calhoun,Consumer,United States,Edinburg,Texas,Central,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,128.368,2,0.8288,0,Online
5260,7966,CA-2020-104864,11/18/2020,11/23/2020,Second Class,JS-15685,Jim Sink,Corporate,United States,Miramar,Florida,South,OFF-PA-10003309,Office Supplies,Paper,Xerox 211,143.472,8,14.5152,0,COD
2721,8590,CA-2020-145338,1/29/2020,2/1/2020,First Class,BD-11770,Bryan Davis,Consumer,United States,Philadelphia,Pennsylvania,East,OFF-AR-10002053,Office Supplies,Art,"Premium Writing Pencils, Soft, #2 by Central A...",102.768,2,0.4768,0,Online
3149,5790,CA-2020-115070,4/10/2020,4/14/2020,Second Class,MG-18205,Mitch Gastineau,Corporate,United States,Jacksonville,Florida,South,OFF-BI-10003712,Office Supplies,Binders,"Acco Pressboard Covers with Storage Hooks, 14 ...",97.419,3,-3.0933,0,Online

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5901
Columns: 21

## Cell 4: Check column names

In [6]:
df.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode'],
      dtype='object')

In [7]:
df.rename(
    columns={"Row ID+O6G3A1:R6": "Row ID"},
    inplace=True
)

In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode'],
      dtype='object')

## Cell 5: Check data types and missing values

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         5901 non-null   int64
 1   Order ID       5901 non-null   object
 2   Order Date     5901 non-null   object
 3   Ship Date      5901 non-null   object
 4   Ship Mode      5901 non-null   object
 5   Customer ID    5901 non-null   object
 6   Customer Name  5901 non-null   object
 7   Segment        5901 non-null   object
 8   Country        5901 non-null   object
 9   City           5901 non-null   object
 10  State          5901 non-null   object
 11  Region         5901 non-null   object
 12  Product ID     5901 non-null   object
 13  Category       5901 non-null   object
 14  Sub-Category   5901 non-null   object
 15  Product Name   5901 non-null   object
 16  Sales          5901 non-null   float64
 17  Quantity       5901 non-null   int64
 18  Profit         5901 non-null   float64
 19  Returns        5901 non-null   int64
 20  Payment Mode   5901 non-null   object
dtypes: float64(2), int64(3), object(16)
memory usage: 968.3+ KB

In [10]:
df.isnull().sum().sort_values(ascending=False)

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Profit           0
Returns          0
Payment Mode     0
dtype: int64

## Cell 6: Check duplicates

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
df.drop_duplicates(inplace=True)

## Cell 7: Convert dates

In [13]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    errors="coerce"
)

In [14]:
df[["Order Date", "Ship Date"]].isnull().sum()

Order Date    0
Ship Date     0
dtype: int64

## Cell 8: Convert numerical columns

In [15]:
numeric_columns = ["Sales", "Quantity", "Profit", "Returns"]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         5901 non-null   int64
 1   Order ID       5901 non-null   object
 2   Order Date     5901 non-null   datetime64[ns]
 3   Ship Date      5901 non-null   datetime64[ns]
 4   Ship Mode      5901 non-null   object
 5   Customer ID    5901 non-null   object
 6   Customer Name  5901 non-null   object
 7   Segment        5901 non-null   object
 8   Country        5901 non-null   object
 9   City           5901 non-null   object
 10  State          5901 non-null   object
 11  Region         5901 non-null   object
 12  Product ID     5901 non-null   object
 13  Category       5901 non-null   object
 14  Sub-Category   5901 non-null   object
 15  Product Name   5901 non-null   object
 16  Sales          5901 non-null   float64
 17  Quantity       5901 non-null   int64
 18  Profit         5901 non-null   float64
 19  Returns        5901 non-null   int64
 20  Payment Mode   5901 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(3), object(14)
memory usage: 968.3+ KB

## Cell 9: Create Shipping Days

In [17]:
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [18]:
df[["Order Date", "Ship Date", "Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2019-01-01 2019-01-07              6
1 2019-01-02 2019-01-07              5
2 2019-01-02 2019-01-07              5
3 2019-01-03 2019-01-05              2
4 2019-01-03 2019-01-08              5

## Cell 10: Create Return Status

In [19]:
df["Return Status"] = np.where(
    df["Returns"] == 1,
    "Returned",
    "Not Returned"
)

## Cell 11: Create Profit Margin %

In [20]:
df["Profit Margin %"] = np.where(
    df["Sales"] != 0,
    (df["Profit"] / df["Sales"]) * 100,
    0
)

## Cell 12: Create date features

In [21]:
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month_name()
df["Order Month No"] = df["Order Date"].dt.month
df["Order Quarter"] = "Q" + df["Order Date"].dt.quarter.astype(str)

## Cell 13: Check invalid values

In [22]:
print("Negative Sales:", (df["Sales"] < 0).sum())
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Negative Shipping Days:", (df["Shipping Days"] < 0).sum())
print("Missing Order Dates:", df["Order Date"].isnull().sum())
print("Missing Ship Dates:", df["Ship Date"].isnull().sum())

Negative Sales: 0
Negative Quantity: 0
Negative Shipping Days: 0
Missing Order Dates: 0
Missing Ship Dates: 0

In [23]:
df[df["Shipping Days"] < 0][
    ["Order ID", "Order Date", "Ship Date", "Shipping Days"]
]

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Shipping Days]
Index: []

## Cell 14: Final data-quality summary

In [24]:
data_quality_summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Duplicate Rows",
        "Missing Values",
        "Negative Sales",
        "Negative Quantity",
        "Negative Shipping Days"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        (df["Sales"] < 0).sum(),
        (df["Quantity"] < 0).sum(),
        (df["Shipping Days"] < 0).sum()
    ]
})

data_quality_summary

                   Metric  Value
0                    Rows   5901
1                 Columns     28
2          Duplicate Rows      0
3          Missing Values      0
4          Negative Sales      0
5       Negative Quantity      0
6  Negative Shipping Days      0

## Cell 15: Save the clean dataset

In [25]:
df.to_csv(
    "../Dataset/clean_amazon_store_sales.csv",
    index=False
)

# Data Cleaning Summary

- Renamed the incorrect Row ID column.
- Checked missing values and duplicate records.
- Converted Order Date and Ship Date into datetime format.
- Converted Sales, Quantity, Profit, and Returns into numerical format.
- Created Shipping Days to measure delivery duration.
- Created Return Status for return analysis.
- Created Profit Margin % for profitability analysis.
- Extracted year, month, month number, and quarter from Order Date.
- Preserved negative profit values because they identify loss-making transactions.
- Exported the cleaned dataset for SQL, Python EDA, and Power BI analysis.